/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:7019bde4-2d06-4c9c-a03a-227fa3d9758f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_MJ0RgXlaO",
    "aws_user_pools_web_client_id": "251batltsmq50m82jvkrt1rr71",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://lpndu2so5bah5bglxw62gt2s4y.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
